# Generated by Django 5.1.6 on 2025-02-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='name',
            field=models.CharField(default='sajjad', max_length=255),
            preserve_default=False,
        ),
    ]
