# Generated by Django 5.1.6 on 2025-02-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_useraccount_follow_useraccount_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='follow',
        ),
    ]
