# Generated by Django 5.1.6 on 2025-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_useraccount_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='posts.useraccount'),
        ),
    ]
