# Generated by Django 5.1.6 on 2025-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_post_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
