# Generated by Django 5.1.6 on 2025-02-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_post_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.useraccount'),
        ),
    ]
