# Generated by Django 5.1.6 on 2025-02-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_comments_is_deleted_alter_comments_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
